Repository authsignal/authsignal-ios, pull requests merged in 2025-08, with the labels that each got.

#52 Handle 404 if no error response provided
  Authsignal.podspec
  README.md
  Sources/Authsignal/API/BaseAPIClient.swift
  Sources/Authsignal/Models/UserActionState.swift
Labels: documentation

#53 Allow passing your own device ID to client
  Authsignal.podspec
  README.md
  Sources/Authsignal/API/BaseAPIClient.swift
  Sources/Authsignal/API/PasskeyAPIClient.swift
  Sources/Authsignal/Authsignal.swift
  Sources/Authsignal/AuthsignalPasskey.swift
Labels: enhancement

#55 Add passkey.isSupported method
  Authsignal.podspec
  Sources/Authsignal/AuthsignalPasskey.swift
Labels: enhancement

#57 Fix encoding of credential ID and handle error code
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  Authsignal.podspec
  README.md
  Sources/Authsignal/Security/PasskeyManager.swift
Labels: bug

#58 Add shouldPromptToCreatePasskey util method
  Authsignal.podspec
  Sources/Authsignal/AuthsignalPasskey.swift
  Sources/Authsignal/Models/SdkErrorCodes.swift
  Sources/Authsignal/Security/PasskeyManager.swift
Labels: enhancement
